# SRC = $(wildcard *.cpp)
# TARGET = main

# all: $(TARGET)

# $(TARGET): $(SRC)
# 	g++ $(SRC) -o $(TARGET)

# run:
# 	./$(TARGET)

# clean:
# 	rm -f $(TARGET)

all:
	g++ main.cpp Account.cpp Savings_Account.cpp Checking_Account.cpp Trust_Account.cpp Account_Util.cpp -o main

clean:
	rm -f main
